### ISSUE TITLE
static: todo

### ISSUE THREAD

**Issue by jonmorehouse** [jonmorehouse/turbo#2]
Here's whats left todo for the static side of this
- [ ] read in startup script
- [ ] switch to use a provisioner for static instances (and write out other instances in the group)
- [ ] add in bootstrap provisioner
- [ ] configure static outputs 
- [ ] fix race condition 
- [ ] build out bastions
- [ ] resolve subnetworks with edge conditions

Once this is done, most of the heavy lifting is done and we can then configure out the dynamic group using alot of the same constructs.
